# TASKING EDE (Windows based integrated Embedded Development Environment)
#
# This makefile has been generated by TASKING EDE
#
# Toolchain: TASKING Tools for C166/ST10 v7.5 r2
#

BINDIR  = z:\c166\soft\tasking\bin
INCDIR  = z:\c166\soft\tasking\include
LIBDIR  = z:\c166\soft\tasking\lib

M166INC = z:\c166\soft\tasking\include
export M166INC
CC166BIN = z:\c166\soft\tasking\bin
export CC166BIN
OPT_IHEX= -c15100h

PROJ    = test
PROJDIR = z:\c166\projects\tasking\.mamaich\flasher
PRODDIR = z:\c166\soft\tasking
OUTDIR  = 

OPT_CC  = -Wcp-I"z:\c166\soft\tasking\include" -Wc-I"z:\c166\soft\tasking\include" -Wc-xmifp -DCPUTYPE=0x167 -Ms -Wc-FSC -noc++ -Wc-OB -Wc-OE -Wc-zautobitastruct-4 -Wc-zautobita-0 -Wc-zswitch_tabmem_default -Wc-s -tmp -Wc-g -Wc-zvolatile_union -Wc-A1 -Wc-O1 -WaPR -WaPL(60) -WaPW(132) -WaTA(8) -WaWA(1) -WaEXTEND -WaNOM166 -WaSN(reg167.def)
OPT_MPP = @'_test.inc' WA(1)
OPT_LC  = "_test.ilo" -cf -libfmtiol -Ms -xmifp -WlNOWA(152) -WoNOWA(152)

all : $(PROJ).hex

test.obj : test.c
	@echo Compiling test.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c test.c
		${separate "\n" $(OPT_CC) }
		EOF

cstart.src : cstart.asm _test.inc
	@echo Preprocessing cstart.asm
		@z:\c166\soft\tasking\bin\m166.exe cstart.asm -f <<EOF
		${separate "\n" $(OPT_MPP) }
		EOF

cstart.obj : cstart.src
	@echo Assembling cstart.src
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c cstart.src
		${separate "\n" $(OPT_CC) }
		EOF

$(PROJ).out : test.obj cstart.obj _test.ilo
	@echo Linking and locating to $*.out
		@z:\c166\soft\tasking\bin\cc166.exe -o $@ -f <<EOF 
		${separate "\n" $(match .obj $!) $(match .lno $!) $(match .lib $!) $(OPT_LC)}
		EOF

$(PROJ).hex : $(PROJ).out
	@echo Converting $*.out to $*.hex in Intel Hex format
		@z:\c166\soft\tasking\bin\ihex166.exe  $(OPT_IHEX) $! $@

# Copyright (c) 2001 Altium, Ltd.
# Serial:	123412-094
# EDE Version:	2.7 r5
