/*
    SieNatJabber Project
 Language
*/
#include "setlang.h"
#ifndef _LANG_H_
#define _LANG_H_

#define LG_COPYRIGHT "Siemens natJabber Client\n(c)Kibab, Ad, Borman99\n%s r%i\nCompiled %s"

///////////////////////////////////////////////////////////////////////////////////////////
//
//    Russian : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_RU
#define LG_SELECT           "Выбор"
#define LG_BACK             "Назад"
#define LG_OK               "OK"
#define LG_CLOSE            "Закрыть"
#define LG_MENU             "Меню"
#define LG_CANCEL           "Отмена"
#define LG_EXIT             "Выход"
#define LG_HELP             "Помощь"
//status_schange.c
#define LG_STATUSSEL        "Выбор статуса"
#define LG_STONLINE         "Онлайн"
#define LG_STCHAT           "Готов болтать"
#define LG_STAWAY           "Отсутсвую"
#define LG_STXA             "Недоступен"
#define LG_STDND            "Занят"
#define LG_STINVIS          "Инвиз"
#define LG_STATUS           "Статус"
#define LG_ENTERTEXTSTATUS  "Введите текст статуса:"
#define LG_PRIORITY         "Приоритет:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "Имя конфы не заполнено!"
#define LG_ENTERMUC         "Вход в MUC"
#define LG_NAMEMUC          "Имя конференции:"
#define LG_NICK             "Ник:"
#define LG_GETMESSAGECOUNT  "Получить сообщений:"
//message_list.c
#define LG_NOSENDNULLMESS   "Нельзя послать пустое сообщение!"
#define LG_NEW              "Новое..."
//message_cmds.c
#define LG_SELCOMMAND       "Выбор команды..."
#define LG_SELTEMPLATE      "Выбор шаблона..."
#define LG_SELSMILE         "Выбор смайла..."
#define LG_SELECT2          "Выбор..."
#define LG_COMMANDS         "Команды"
#define LG_MSGTEMPLATE      "Шаблоны сообщений"
#define LG_SMILE            "Смайлы"
#define LG_CLOSEDLG         "Закрыть диалог"
//mainmenu.c
#define LG_CONTACT          "Контакт"
#define LG_STATUS           "Статус"
#define LG_MUC              "Конференция"
#define LG_BOOKMARK         "Закладки"
#define LG_MVIBRA           "Режим вибры"
#define LG_MSOUND           "Режим звука"
#define LG_MOFFLINE         "Офф. контакты"
#define LG_SETTINGS         "Настройки"
#define LG_ABOUT            "Об эльфе..."
//main.c
#define LG_EXITSIEJC        "Покинуть SieJC?"
#define LG_ZLIBNOSASL       "ZLib не работает без SASL!"
#define LG_ENTERLOGPAS      "Введите логин/пароль!"
#define LG_PLATFORMM        "Платформа не соответствует!"
//jabber_util.c
#define LG_MUCEXITDONE      "Выход из MUC выполнен!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
//item_info.c
#define LG_ELROSTER         "Элемент ростера"
#define LG_OFFLORCONTTR     "Оффлайн или контакт из транспорта"
#define LG_MUCPART          "Участник конференции"
#define LG_JTRANSP          "Данный контакт является транспортом Jabber"
#define LG_GROUPROSTER      "Группа ростера"
#define LG_RESOURCE         "Ресурс:"
#define LG_PRIORITY         "Приоритет:"
#define LG_REALJID          "Реальный JID:"
#define LG_STATUS2          "Статус:"
#define LG_PRIVILEGES       "Привилегии:"
#define LG_ROLE             "Роль:"
#define LG_POSIBLCLIENT     "Возможности клиента:"
//history.c
#define LG_ERRORWH          "Ошибка I/O #%u при записи истории!"
//cont_menu.c
#define LG_MENUCONTACT      "Меню контакта"
#define LG_UNKACTION        "Действие неизвестно или не поддерживается!"
#define LG_ABANDON          "Покинуть"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Кик"
#define LG_BAN              "Бан"
#define LG_LVOISE           "Отнять голос"
#define LG_GVOISE           "Дать голос"
#define LG_PARTICIPANT      "Participant"
#define LG_MEMBER           "Member"
#define LG_MODERATOR        "Moderator"
#define LG_ADMIN            "Admin"
#define LG_OWNER            "Owner"
#define LG_VERCLIENT        "Версия клиента"
#define LG_INFOFDISC        "Инфо из Disco"
#define LG_ON               "Включить"
#define LG_OFF              "Отключить"
#define LG_NOSUPACTION      "Нет поддерживаемых действий"
#define LG_OHISTORY         "История"
#define LG_QUERYTIME        "Время клиента"
#define LG_QUERYVCARD       "vCard"
//clist_util.c
#define LG_AUTHORREM        "В авторизации отказано!"
#define LG_AUTHORGRANTED    "Авторизация дана!"
#define LG_MUCCROK          "Конференция создана успешно"
//bookmarks.c
#define LG_MENUBOOKMARK     "Меню закладок"
//config_data.c
#define LG_NO               "Нет"
#define LG_YES              "Да"
#define LG_DISABLED         "Отключить"
#define LG_ENABLED          "Включить"

#define LG_SETUPCONECT      "Настройка подключения"
#define LG_LOGIN            "Логин"
#define LG_PASSWORD         "Пароль"
#define LG_SERVER           "Сервер"
#define LG_HOST             "Хост"
#define LG_HOSTTYPE         "Тип хоста"
#define LG_HOSTNAME         "Имя"
#define LG_IPADRESS         "IP адрес"
#define LG_PORT             "Порт"
#define LG_AUTHTYPE         "Авторизация"
#define LG_ZLIBUSE          "Использование ZLib"
#define LG_RES              "Ресурс"
#define LG_HISTORY          "История"
#define LG_MUCHIST          "MUC история"
#define LG_MUCDEF           "MUC по умолчанию"
#define LG_MUCDEFNIK        "Ник поумолчанию"
#define LG_IDLEICON         "Положение значка"
#define LG_POPUPDIS         "Отображать POPUP"
#define LG_COMPOSEV         "События сообщений"
#define LG_DELIVREP         "Delivery Report if required"

#define LG_SETUPSND         "Настройка звука"
#define LG_SNDVOL           "Громкость"
#define LG_SNDMSGSND        "Звук отправки"
#define LG_SNDMSGMUC        "Звук приема из MUC"
#define LG_SNDMSGPM         "Звук приема из PM"

#define LG_SETUPPATH        "Настройка путей"
#define LG_PATHHIST         "История"
#define LG_PATHPIC          "Картинки"
#define LG_PATHCMD          "Команды"
#define LG_PATHMESG         "Собщения"
#define LG_PATHKNOWF        "Известные особенности"
#define LG_PATHSMILECFG     "Конфиг смайлов"
#define LG_PATHSMILEDIR     "Каталог смайлов"
#define LG_DEFUALTDISK      "Диск по умолчанию"

#define LG_TEXTSTATUS       "Текст статусов"
#define LG_DEFSTATES        "Состояния по умолчанию"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Полное имя"
#define LG_VCARD_NICKNAME   "Ник"
#define LG_VCARD_BDAY       "День рождения"
#define LG_VCARD_GENDER     "Пол"
#define LG_VCARD_ORGNAME    "Название организации"
#define LG_VCARD_ORGUNIT    "Отделение организации"
#define LG_VCARD_TITLE      "Название должности"
#define LG_VCARD_ROLE       "Должность"
#define LG_VCARD_EMAIL      "E-Mail"
#define LG_VCARD_URL        "Домашняя страница"
#define LG_VCARD_DESC       "О себе"

#endif //RU

///////////////////////////////////////////////////////////////////////////////////////////
//
//    Ukrainian : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_UA
#define LG_SELECT           "Вибір"
#define LG_BACK             "Назад"
#define LG_OK               "Добре"
#define LG_CLOSE            "Закрити"
#define LG_MENU             "Меню"
#define LG_CANCEL           "Відмінити"
#define LG_EXIT             "Вихід"
#define LG_HELP             "Допомога"
//status_schange.c
#define LG_STATUSSEL        "Вибір статусу"
#define LG_STONLINE         "В мережі"
#define LG_STCHAT           "Готовий до розмови"
#define LG_STAWAY           "Відсутній"
#define LG_STXA             "Недоступний"
#define LG_STDND            "Зайнятий"
#define LG_STINVIS          "Невидимий"
#define LG_STATUS           "Статус"
#define LG_ENTERTEXTSTATUS  "Введіть текст статусу:"
#define LG_PRIORITY         "Приоритет:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "Им'я конференції не заповнено!"
#define LG_ENTERMUC         "Вхід в MUC"
#define LG_NAMEMUC          "Им'я конференції:"
#define LG_NICK             "Нік:"
#define LG_GETMESSAGECOUNT  "Отримати повідомлень:"
//message_list.c
#define LG_NOSENDNULLMESS   "Не можна відіслати порожнє повідомлення!"
#define LG_NEW              "Нове..."
//message_cmds.c
#define LG_SELCOMMAND       "Вибір команди..."
#define LG_SELTEMPLATE      "Вибір шаблону..."
#define LG_SELSMILE         "Вибір смайлу..."
#define LG_SELECT2          "Вибір..."
#define LG_COMMANDS         "Команди"
#define LG_MSGTEMPLATE      "Шаблони повідомлень"
#define LG_SMILE            "Смайли"
#define LG_CLOSEDLG         "Закрити діалог"
//mainmenu.c
#define LG_CONTACT          "Контакт"
#define LG_STATUS           "Статус"
#define LG_MUC              "Конференція"
#define LG_BOOKMARK         "Закладки"
#define LG_MVIBRA           "Режим вібри"
#define LG_MSOUND           "Режим звуку"
#define LG_MOFFLINE         "Офф. контакти"
#define LG_SETTINGS         "Налаштування"
#define LG_ABOUT            "Про эльф..."
//main.c
#define LG_EXITSIEJC        "Покинути SieJC?"
#define LG_ZLIBNOSASL       "ZLib не працює без SASL!"
#define LG_ENTERLOGPAS      "Введіть логін/пароль!"
#define LG_PLATFORMM        "Платформа не відповідає!"
//jabber_util.c
#define LG_MUCEXITDONE      "Вихід из MUC виконано!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
//item_info.c
#define LG_ELROSTER         "Елемент ростеру"
#define LG_OFFLORCONTTR     "Оффлайн або контакт із транспорту"
#define LG_MUCPART          "Учасник конференції"
#define LG_JTRANSP          "Данний контакт є транспортом Jabber"
#define LG_GROUPROSTER      "Група ростеру"
#define LG_RESOURCE         "Ресурс:"
#define LG_PRIORITY         "Приоритет:"
#define LG_REALJID          "Реальний JID:"
#define LG_STATUS2          "Статус:"
#define LG_PRIVILEGES       "Привілеї:"
#define LG_ROLE             "Роль:"
#define LG_POSIBLCLIENT     "Можливості клієнта:"
//history.c
#define LG_ERRORWH          "Помилка I/O #%u при запису історії!"
//cont_menu.c
#define LG_MENUCONTACT      "Меню контакту"
#define LG_UNKACTION        "Дія невідома або не підтримується!"
#define LG_ABANDON          "Покинути"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Кік"
#define LG_BAN              "Бан"
#define LG_LVOISE           "Відняти голос"
#define LG_GVOISE           "Дати голос"
#define LG_PARTICIPANT      "Participant"
#define LG_MEMBER           "Member"
#define LG_MODERATOR        "Moderator"
#define LG_ADMIN            "Admin"
#define LG_OWNER            "Owner"
#define LG_VERCLIENT        "Версія клієнту"
#define LG_INFOFDISC        "Інфо із Disco"
#define LG_ON               "Включити"
#define LG_OFF              "Відключити"
#define LG_NOSUPACTION      "Немає підтримуваних дій"
#define LG_OHISTORY         "Історія"
#define LG_QUERYTIME        "Час"
#define LG_QUERYVCARD       "vCard"
//clist_util.c
#define LG_AUTHORREM        "В авторизації відмовлено!"
#define LG_AUTHORGRANTED    "Авторизація дана!"
#define LG_MUCCROK          "Конференція створена успішно"
//bookmarks.c
#define LG_MENUBOOKMARK     "Меню закладок"
//config_data.c
#define LG_NO               "Ні"
#define LG_YES              "Так"
#define LG_DISABLED         "Відключити"
#define LG_ENABLED          "Включити"

#define LG_SETUPCONECT      "Налаштування підключення"
#define LG_LOGIN            "Логін"
#define LG_PASSWORD         "Пароль"
#define LG_SERVER           "Сервер"
#define LG_HOST             "Хост"
#define LG_HOSTTYPE         "Тип хосту"
#define LG_HOSTNAME         "Им'я"
#define LG_IPADRESS         "IP адреса"
#define LG_PORT             "Порт"
#define LG_AUTHTYPE         "Авторизація"
#define LG_ZLIBUSE          "Використання ZLib"
#define LG_RES              "Ресурс"  // Если не так, сильно не бейте
#define LG_HISTORY          "Історія"
#define LG_MUCHIST          "MUC історія"
#define LG_MUCDEF           "MUC за умовчанням"
#define LG_MUCDEFNIK        "Нік за умовчанням"
#define LG_IDLEICON         "Розташування значка"
#define LG_POPUPDIS         "Відображати POPUP"
#define LG_COMPOSEV         "Події повідомлень"
#define LG_DELIVREP         "Delivery Report if required"

#define LG_SETUPSND         "Налаштування звуку"
#define LG_SNDVOL           "Гучність"
#define LG_SNDMSGSND        "Звук відправки"
#define LG_SNDMSGMUC        "Звук прийому із MUC"
#define LG_SNDMSGPM         "Звук прийому із PM"

#define LG_SETUPPATH        "Налаштування шляхів"
#define LG_PATHHIST         "Історія"
#define LG_PATHPIC          "Картинки"
#define LG_PATHCMD          "Команди"
#define LG_PATHMESG         "Повідомлення"
#define LG_PATHKNOWF        "Відомі особливості"
#define LG_PATHSMILECFG     "Конфіг смайлів"
#define LG_PATHSMILEDIR     "Каталог смайлів"
#define LG_DEFUALTDISK      "Диск за умовчанням"

#define LG_TEXTSTATUS       "Текст статусів"
#define LG_DEFSTATES        "Стани за умовчанням"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Повне ім'я"
#define LG_VCARD_NICKNAME   "Нік"
#define LG_VCARD_BDAY       "День народження"
#define LG_VCARD_GENDER     "Стать"
#define LG_VCARD_ORGNAME    "Назва організації"
#define LG_VCARD_ORGUNIT    "Відділ організації"
#define LG_VCARD_TITLE      "Назва посади"
#define LG_VCARD_ROLE       "Посада"
#define LG_VCARD_EMAIL      "E-Mail"
#define LG_VCARD_URL        "Домашня сторінка"
#define LG_VCARD_DESC       "Про себе"
#endif //UA

///////////////////////////////////////////////////////////////////////////////////////////
//
//    English : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_EN
#define LG_SELECT           "Select"
#define LG_BACK             "Back"
#define LG_OK               "OK"
#define LG_CLOSE            "Close"
#define LG_MENU             "Menu"
#define LG_CANCEL           "Cancel"
#define LG_EXIT             "Exit"
#define LG_HELP             "Help"
//status_schange.c
#define LG_STATUSSEL        "Choice of status"
#define LG_STONLINE         "Online"
#define LG_STCHAT           "Chat"
#define LG_STAWAY           "Away"
#define LG_STXA             "Xa"
#define LG_STDND            "Dnd"
#define LG_STINVIS          "Invisible"
#define LG_STATUS           "Statuse"
#define LG_ENTERTEXTSTATUS  "Enter text status:"
#define LG_PRIORITY         "Priority:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "A conference name is not filled!"
#define LG_ENTERMUC         "Enter in MUC"
#define LG_NAMEMUC          "Name MUC:"
#define LG_NICK             "Nick:"
#define LG_GETMESSAGECOUNT  "To get messages:"
//message_list.c
#define LG_NOSENDNULLMESS   "It is impossible to send the empty message!"
#define LG_NEW              "New..."
//message_cmds.c
#define LG_SELCOMMAND       "Select commands..."
#define LG_SELTEMPLATE      "Select template..."
#define LG_SELSMILE         "Select smile..."
#define LG_SELECT2          "Select..."
#define LG_COMMANDS         "Commands"
#define LG_MSGTEMPLATE      "Templates messages"
#define LG_SMILE            "Smiles"
#define LG_CLOSEDLG         "Close a dialog"
//mainmenu.c
#define LG_CONTACT          "Contact"
#define LG_STATUS           "Statuse"
#define LG_MUC              "MUC"
#define LG_BOOKMARK         "Bookmark"
#define LG_MVIBRA           "Vibra mode"
#define LG_MSOUND           "Sound mode"
#define LG_MOFFLINE         "Show Offline"
#define LG_SETTINGS         "Settings"
#define LG_ABOUT            "About..."
//main.c
#define LG_EXITSIEJC        "Exit SieJC?"
#define LG_ZLIBNOSASL       "ZLib don't work without SASL!"
#define LG_ENTERLOGPAS      "Enter login/password!"
#define LG_PLATFORMM        "Target platform mismatch!"
//jabber_util.c
#define LG_MUCEXITDONE      "Exit from MUC execute!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
//item_info.c
#define LG_ELROSTER         "Roster elements"
#define LG_OFFLORCONTTR     "Offline or contact from transport"
#define LG_MUCPART          "MUC partcipiant"
#define LG_JTRANSP          "This contact is Jabber transport"
#define LG_GROUPROSTER      "Roster group"
#define LG_RESOURCE         "Resource:"
#define LG_PRIORITY         "Priority:"
#define LG_REALJID          "Real JID:"
#define LG_STATUS2          "Statuse:"
#define LG_PRIVILEGES       "Privileges:"
#define LG_ROLE             "Role:"
#define LG_POSIBLCLIENT     "Possibilities of client:"
//history.c
#define LG_ERRORWH          "Error I/O #%u at the history record!"
//cont_menu.c
#define LG_MENUCONTACT      "Contact menu"
#define LG_UNKACTION        "Unkcnow action or no support!"
#define LG_ABANDON          "Leave MUC"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Kik"
#define LG_BAN              "Ban"
#define LG_LVOISE           "Away voice"
#define LG_GVOISE           "Get voice"
#define LG_PARTICIPANT      "Participant"
#define LG_MEMBER           "Member"
#define LG_MODERATOR        "Moderator"
#define LG_ADMIN            "Admin"
#define LG_OWNER            "Owner"
#define LG_VERCLIENT        "Version"
#define LG_INFOFDISC        "Info from Disco"
#define LG_ON               "Connect"
#define LG_OFF              "Disconnect"
#define LG_NOSUPACTION      "No support action"
#define LG_OHISTORY         "History"
#define LG_QUERYTIME        "Time"
#define LG_QUERYVCARD       "vCard"
//clist_util.c
#define LG_AUTHORREM        "Authorization was removed!"
#define LG_AUTHORGRANTED    "Authorization was granted!"
#define LG_MUCCROK          "Conference created OK!"
//bookmarks.c
#define LG_MENUBOOKMARK     "Bookmark menu"
//config_data.c
#define LG_NO               "No"
#define LG_YES              "Yes"
#define LG_DISABLED         "Disabled"
#define LG_ENABLED          "Enabled"

#define LG_SETUPCONECT      "Connection setup"
#define LG_LOGIN            "Login"
#define LG_PASSWORD         "Password"
#define LG_SERVER           "Server"
#define LG_HOST             "Host"
#define LG_HOSTTYPE         "Host type"
#define LG_HOSTNAME         "Host name"
#define LG_IPADRESS         "IP address"
#define LG_PORT             "Port"
#define LG_AUTHTYPE         "Auth type"
#define LG_ZLIBUSE          "ZLib usage"
#define LG_RES              "Resource"
#define LG_HISTORY          "History"
#define LG_MUCHIST          "MUC history"
#define LG_MUCDEF           "Default MUC"
#define LG_MUCDEFNIK        "Default MUC nick"
#define LG_IDLEICON         "Idle icon position"
#define LG_POPUPDIS         "Display pop-ups"
#define LG_COMPOSEV         "Composing Events"
#define LG_DELIVREP         "Delivery Report if required"

#define LG_SETUPSND         "Sounds setup"
#define LG_SNDVOL           "sndVolume"
#define LG_SNDMSGSND        "Sound Msg Send"
#define LG_SNDMSGMUC        "Sound Msg Conf"
#define LG_SNDMSGPM         "Sound Msg PM"

#define LG_SETUPPATH        "Paths setup"
#define LG_PATHHIST         "History path"
#define LG_PATHPIC          "Pictures path"
#define LG_PATHCMD          "Commands path"
#define LG_PATHMESG         "Messages path"
#define LG_PATHKNOWF        "Known features"
#define LG_PATHSMILECFG     "Smiles config"
#define LG_PATHSMILEDIR     "Smiles .png path"
#define LG_DEFUALTDISK      "Default disc"

#define LG_TEXTSTATUS       "Statuses text"
#define LG_DEFSTATES        "Default states"

// vCard.c

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Full name"
#define LG_VCARD_NICKNAME   "Nickname"
#define LG_VCARD_BDAY       "Birthday"
#define LG_VCARD_GENDER     "Gender"
#define LG_VCARD_ORGNAME    "Org. name"
#define LG_VCARD_ORGUNIT    "Org. unit"
#define LG_VCARD_TITLE      "Title"
#define LG_VCARD_ROLE       "Role"
#define LG_VCARD_EMAIL      "E-Mail"
#define LG_VCARD_URL        "Homepage"
#define LG_VCARD_DESC       "Description"
#endif //EN


#endif