# TASKING EDE (Windows based integrated Embedded Development Environment)
#
# This makefile has been generated by TASKING EDE
#
# Toolchain: TASKING Tools for C166/ST10 v7.5 r2
#

BINDIR  = z:\c166\soft\tasking\bin
INCDIR  = z:\c166\soft\tasking\include
LIBDIR  = z:\c166\soft\tasking\lib

M166INC = z:\c166\soft\tasking\include
export M166INC
CC166BIN = z:\c166\soft\tasking\bin
export CC166BIN
OPT_IHEX= -c0h

PROJ    = test
PROJDIR = z:\c166\projects\tasking\uni2
PRODDIR = z:\c166\soft\tasking
OUTDIR  = 

OPT_CC  = -Wcp-I"z:\c166\soft\tasking\include" -Wc-I"z:\c166\soft\tasking\include" -Wc-xmifp -DCPUTYPE=0x167 -Ml -Wc-FSC -noc++ -Wc-OB -Wc-znocustack -Wc-zautobitastruct-4 -Wc-zautobita-0 -Wc-T256 -Wc-s -tmp -Wc-g -Wc-zvolatile_union -Wc-A1 -Wc-O3 -WaPR -WaPL(60) -WaPW(132) -WaTA(8) -WaWA(0) -WaEXTEND -WaSG
OPT_MPP = @'_test.inc' WA(1)
OPT_LC  = "_test.ilo" -cf -nolib -Ml -xmifp

all : $(PROJ).hex

common.obj : z:\c166\projects\tasking\uni2\packages\common\common.c z:\c166\soft\tasking\include\reg167.h
common.obj : z:\c166\projects\tasking\uni2\packages\common\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\common\common.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\common\common.c
		${separate "\n" $(OPT_CC) }
		EOF

cstart.src : z:\c166\projects\tasking\uni2\packages\common\cstart.asm _test.inc
	@echo Preprocessing z:\c166\projects\tasking\uni2\packages\common\cstart.asm
		@z:\c166\soft\tasking\bin\m166.exe z:\c166\projects\tasking\uni2\packages\common\cstart.asm -f <<EOF
		${separate "\n" $(OPT_MPP) }
		EOF

cstart.obj : cstart.src
	@echo Assembling cstart.src
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c cstart.src
		${separate "\n" $(OPT_CC) }
		EOF

dialogs.obj : z:\c166\projects\tasking\uni2\packages\dialogs\dialogs.c z:\c166\soft\tasking\include\reg167.h
dialogs.obj : z:\c166\projects\tasking\uni2\packages\dialogs\..\..\include\_sl45.h
dialogs.obj : z:\c166\projects\tasking\uni2\packages\dialogs\..\..\include\heaps.h
dialogs.obj : z:\c166\projects\tasking\uni2\packages\dialogs\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\dialogs\dialogs.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\dialogs\dialogs.c
		${separate "\n" $(OPT_CC) }
		EOF

files.obj : z:\c166\projects\tasking\uni2\packages\files\files.c z:\c166\soft\tasking\include\reg167.h
files.obj : z:\c166\projects\tasking\uni2\packages\files\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\files\..\..\include\heaps.h
files.obj : z:\c166\projects\tasking\uni2\packages\files\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\files\files.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\files\files.c
		${separate "\n" $(OPT_CC) }
		EOF

keys.obj : z:\c166\projects\tasking\uni2\packages\keys\keys.c z:\c166\soft\tasking\include\reg167.h
keys.obj : z:\c166\projects\tasking\uni2\packages\keys\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\keys\..\..\include\heaps.h
keys.obj : z:\c166\projects\tasking\uni2\packages\keys\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\keys\keys.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\keys\keys.c
		${separate "\n" $(OPT_CC) }
		EOF

passwords.obj : z:\c166\projects\tasking\uni2\packages\passwords\passwords.c z:\c166\soft\tasking\include\reg167.h
passwords.obj : z:\c166\projects\tasking\uni2\packages\passwords\..\..\include\_sl45.h
passwords.obj : z:\c166\projects\tasking\uni2\packages\passwords\..\..\include\heaps.h
passwords.obj : z:\c166\projects\tasking\uni2\packages\passwords\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\passwords\passwords.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\passwords\passwords.c
		${separate "\n" $(OPT_CC) }
		EOF

screen.obj : z:\c166\projects\tasking\uni2\packages\screen\screen.c z:\c166\soft\tasking\include\reg167.h
screen.obj : z:\c166\projects\tasking\uni2\packages\screen\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\screen\..\..\include\heaps.h
screen.obj : z:\c166\projects\tasking\uni2\packages\screen\..\..\include\_uni2.h z:\c166\projects\tasking\uni2\packages\screen\bmp_screen.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\screen\screen.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\screen\screen.c
		${separate "\n" $(OPT_CC) }
		EOF

setup.obj : z:\c166\projects\tasking\uni2\packages\setup\setup.c z:\c166\soft\tasking\include\reg167.h
setup.obj : z:\c166\projects\tasking\uni2\packages\setup\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\setup\..\..\include\heaps.h
setup.obj : z:\c166\projects\tasking\uni2\packages\setup\..\..\include\_uni2.h z:\c166\projects\tasking\uni2\packages\setup\bmp_setup.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\setup\setup.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\setup\setup.c
		${separate "\n" $(OPT_CC) }
		EOF

system.obj : z:\c166\projects\tasking\uni2\packages\system\system.c z:\c166\soft\tasking\include\reg167.h
system.obj : z:\c166\projects\tasking\uni2\packages\system\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\system\..\..\include\heaps.h
system.obj : z:\c166\projects\tasking\uni2\packages\system\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\system\system.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\system\system.c
		${separate "\n" $(OPT_CC) }
		EOF

timers.obj : z:\c166\projects\tasking\uni2\packages\timers\timers.c z:\c166\soft\tasking\include\reg167.h
timers.obj : z:\c166\projects\tasking\uni2\packages\timers\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\timers\..\..\include\heaps.h
timers.obj : z:\c166\projects\tasking\uni2\packages\timers\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\timers\timers.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\timers\timers.c
		${separate "\n" $(OPT_CC) }
		EOF

gsn_f.obj : z:\c166\projects\tasking\uni2\packages\gsn_f\gsn_f.c z:\c166\soft\tasking\include\reg167.h
gsn_f.obj : z:\c166\projects\tasking\uni2\packages\gsn_f\..\..\include\_sl45.h z:\c166\projects\tasking\uni2\packages\gsn_f\..\..\include\heaps.h
gsn_f.obj : z:\c166\projects\tasking\uni2\packages\gsn_f\..\..\include\_uni2.h z:\c166\projects\tasking\uni2\packages\gsn_f\flasher\boot.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\gsn_f\gsn_f.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\gsn_f\gsn_f.c
		${separate "\n" $(OPT_CC) }
		EOF

mp3_playlist.obj : z:\c166\projects\tasking\uni2\packages\mp3_playlist\mp3_playlist.c
mp3_playlist.obj : z:\c166\soft\tasking\include\reg167.h z:\c166\projects\tasking\uni2\packages\mp3_playlist\..\..\include\_sl45.h
mp3_playlist.obj : z:\c166\projects\tasking\uni2\packages\mp3_playlist\..\..\include\heaps.h
mp3_playlist.obj : z:\c166\projects\tasking\uni2\packages\mp3_playlist\..\..\include\_uni2.h
	@echo Compiling z:\c166\projects\tasking\uni2\packages\mp3_playlist\mp3_playlist.c
		@z:\c166\soft\tasking\bin\cc166.exe -f <<EOF -c z:\c166\projects\tasking\uni2\packages\mp3_playlist\mp3_playlist.c
		${separate "\n" $(OPT_CC) }
		EOF

$(PROJ).out : common.obj cstart.obj dialogs.obj files.obj keys.obj passwords.obj screen.obj
$(PROJ).out : setup.obj system.obj timers.obj gsn_f.obj mp3_playlist.obj _test.ilo
	@echo Linking and locating to $*.out
		@z:\c166\soft\tasking\bin\cc166.exe -o $@ -f <<EOF 
		${separate "\n" $(match .obj $!) $(match .lno $!) $(match .lib $!) $(OPT_LC)}
		EOF

$(PROJ).hex : $(PROJ).out
	@echo Converting $*.out to $*.hex in Intel Hex format
		@z:\c166\soft\tasking\bin\ihex166.exe  $(OPT_IHEX) $! $@

# Copyright (c) 2001 Altium, Ltd.
# Serial:	123412-094
# EDE Version:	2.7 r5
